<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>ItsDaveB</Authors>
    <Company>ItsDaveB</Company>
    <Copyright>Copyright (c) ItsDaveB</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ItsDaveB/OgmiosDotnet.BlockchainEvents</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ItsDaveB/OgmiosDotnet.BlockchainEvents</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>cardano;ogmios;blockchain;events;cloudevents;filtering</PackageTags>
    <Version>1.0.1</Version>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
