services:
  blockchain-events:
    build:
      context: .
      dockerfile: src/BlockchainEvents.Worker/Dockerfile
      target: runtime-debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined

  demo-subscriber:
    build:
      context: .
      dockerfile: tools/BlockchainEvents.DemoSubscriber/Dockerfile
      target: runtime-debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
